#!/usr/bin/env bash
# This script displays username, user id and home directory from /etc/passwd
while IFS=: read -r username password uid gid gecos home shell
do
  : "$password" "$gid" "$gecos" "$shell"
  echo "$username:$uid:$home"
done < /etc/passwd
